build:
  version: "3.0"

#  this will be prefix for AccountsContactInfoDto
accounts:
  message: "Welcome to the PROD Env."
  env: "PROD"
  contactDetails:
    name: "Bickey Manandhar - Production Lead"
    email: "xyz@gmail.com"
  onCallSupport:
    - (923)456-7891
    - (434)567-8910
