build:
  version: "2.0"

#  this will be prefix for AccountsContactInfoDto
accounts:
  message: "Welcome to the QA env."
  env: "QA"
  contactDetails:
    name: "Bickey Manandhar - QA Lead"
    email: "xyz@gmail.com"
  onCallSupport:
    - (723)456-7891
    - (834)567-8910
